### ISSUE TITLE
Cross Browser Compatibility

### ISSUE THREAD

**Issue by apreist14** [luckydesignlady/web-iv-portfolio-site#1]
unsatisfactory- does not function in firefox. The grid is broke in firefox the images do not align. There is an awkward half horizontal scroll. Also it makes your footer super big, the google plus icon is outside the grid, and the copyright is off the page.

**Comment by luckydesignlady** [comment]
That's so strange. I just double-checked it in my firefox, and it looks fine :(
I'll have to double-check that framework's grid works with firefox properly, I guess

**Comment by e-m-durham** [comment]
@apreist14 could you try taking a screen cap and tell us which version of Firefox you are using?
