### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by apreist14** [luckydesignlady/web-iv-portfolio-site#3]
Advanced
- All components of the site function properly and are operating as intended. I don't see anything that isn't working properly. All links are functioning.

**Comment by e-m-durham** [comment]
It might be nice to make your email address a link—but that overlaps with UX. Your navigation doesn't seem to be expanding on smaller screen sizes as a user would expect. Currently, the pagination does not function but with the other feedback you may be considering an alternate solution for that anyway.
