### ISSUE TITLE
Responsiveness 

### ISSUE THREAD

**Issue by apreist14** [luckydesignlady/web-iv-portfolio-site#4]
Satisfactory
- There are some issues that may cause problems on certain devices. When the home page is in mobile the top two images get itty bitty and you can hardly see them. 

-Also I would consider making the previous and next turn into big clickable buttons instead of what they are now. I don't think someone with big fingers would be able to click the 1 2 3 4. 

-On the home page I think that the project images may need to be a bit smaller.. It just seems like a super long scroll right now but would need to test it on a phone to actually see if it is a major problem or not.

**Comment by e-m-durham** [comment]
I agree with the pagination, that'd be pretty difficult to use on smaller screens. I'm not sure it makes sense from a user experience standpoint either. In pagination we'd expect a list of results in most applications.

The image grid on your homepage isn't reflecting your wireframes, so I'm guessing that's an area you are still working on but ashley is right, that for now the size of your thumbnails on small screens would be indecipherable for the user.

Maybe there is a way to simplify the layout on the homepage and bring down your number of images closer to ten. 

I'm not sure you're going to want your content to expand all the way across the browser, some breathing room on the margins might be nice to make it more comfortable to read through especially on the project page.
