### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by apreist14** [luckydesignlady/web-iv-portfolio-site#6]
Advanced
- All HTML elements are used in context and there is an appropriate hierarchy, consistent naming conventions and all the labels are descriptive and consistent. 
- I don't see any problems with the semantics of your code.

**Comment by e-m-durham** [comment]
Yep, it's looking really good here but you might want to reconsider how you are marking up the title/subtile on your project page. http://html5doctor.com/howto-subheadings/

**Comment by luckydesignlady** [comment]
![screen shot 2015-05-16 at 11 46 43 am](https://cloud.githubusercontent.com/assets/8355247/7687270/b0902c70-fd61-11e4-9077-bb6717421b18.png)
This is tough for me to figure out every darn time! Is this better?
