### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by apreist14** [luckydesignlady/web-iv-portfolio-site#8]
Satisfactory
- I think that on the main page your images may be a little too small. I want to be able to see your work and get a good idea of what it is before clicking on the project and reading more about it. Right now I can see that it is an identity system but I can not hardly see the logo. Bigger more engaging images will make me want to see more of your work. If you would make the space between the columns smaller that would also help a lot. 

-Is there a reason that your work images don't align? I am assuming that you want them to align nicely with the columns but didn't go the way you wanted. 

-Your line lengths are a little too long on your home page. 

-Social media icons are too big. Looking at hierarchy I don't think the need to be as big as your headings and work images. 

-Other than that just working on spacing placing and size fine-tuning those details and you should be good to go!

**Comment by e-m-durham** [comment]
I agree with @apreist14 here and will echo a couple of our  previous comments of those images being too small. You really want to use each screen size to your advantage to make a pleasant viewing experience, focused on your work, for the user. The line lengths do become uncomfortable to read and you'll want to work out those sizing/spacing/alignment issues.

Also, as commented from before, the pagination doesn't seem to make as much sense from a UX standpoint.
